name: Maisy
favicon: null
layout_spectrum: 0.20988744660280645
typography_spectrum: 0.36888758721761405
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6251536146737635
  lightness: 0.5160968897398561
  saturation: 0.5546521130017936
  rhythmicContrast: 0.11211989400908351
purpose: []
